python /afs/cern.ch/work/e/ecasilar/GplusbJets/control_plotter.py --plot=0 --region=single_photon
python /afs/cern.ch/work/e/ecasilar/GplusbJets/control_plotter.py --plot=1 --region=single_photon
python /afs/cern.ch/work/e/ecasilar/GplusbJets/control_plotter.py --plot=2 --region=single_photon
python /afs/cern.ch/work/e/ecasilar/GplusbJets/control_plotter.py --plot=3 --region=single_photon
python /afs/cern.ch/work/e/ecasilar/GplusbJets/control_plotter.py --plot=4 --region=single_photon
python /afs/cern.ch/work/e/ecasilar/GplusbJets/control_plotter.py --plot=5 --region=single_photon
python /afs/cern.ch/work/e/ecasilar/GplusbJets/control_plotter.py --plot=6 --region=single_photon
python /afs/cern.ch/work/e/ecasilar/GplusbJets/control_plotter.py --plot=7 --region=single_photon
python /afs/cern.ch/work/e/ecasilar/GplusbJets/control_plotter.py --plot=8 --region=single_photon
python /afs/cern.ch/work/e/ecasilar/GplusbJets/control_plotter.py --plot=9 --region=single_photon
python /afs/cern.ch/work/e/ecasilar/GplusbJets/control_plotter.py --plot=10 --region=single_photon
python /afs/cern.ch/work/e/ecasilar/GplusbJets/control_plotter.py --plot=11 --region=single_photon
python /afs/cern.ch/work/e/ecasilar/GplusbJets/control_plotter.py --plot=0	   --region=0b
python /afs/cern.ch/work/e/ecasilar/GplusbJets/control_plotter.py --plot=1	   --region=0b
python /afs/cern.ch/work/e/ecasilar/GplusbJets/control_plotter.py --plot=2	   --region=0b
python /afs/cern.ch/work/e/ecasilar/GplusbJets/control_plotter.py --plot=3	   --region=0b
python /afs/cern.ch/work/e/ecasilar/GplusbJets/control_plotter.py --plot=4	   --region=0b
python /afs/cern.ch/work/e/ecasilar/GplusbJets/control_plotter.py --plot=5	   --region=0b
python /afs/cern.ch/work/e/ecasilar/GplusbJets/control_plotter.py --plot=6	   --region=0b
python /afs/cern.ch/work/e/ecasilar/GplusbJets/control_plotter.py --plot=7	   --region=0b
python /afs/cern.ch/work/e/ecasilar/GplusbJets/control_plotter.py --plot=8	   --region=0b
python /afs/cern.ch/work/e/ecasilar/GplusbJets/control_plotter.py --plot=9	   --region=0b
python /afs/cern.ch/work/e/ecasilar/GplusbJets/control_plotter.py --plot=10	   --region=0b
python /afs/cern.ch/work/e/ecasilar/GplusbJets/control_plotter.py --plot=11	   --region=0b
python /afs/cern.ch/work/e/ecasilar/GplusbJets/control_plotter.py --plot=0	   --region=1b
python /afs/cern.ch/work/e/ecasilar/GplusbJets/control_plotter.py --plot=1	   --region=1b
python /afs/cern.ch/work/e/ecasilar/GplusbJets/control_plotter.py --plot=2	   --region=1b
python /afs/cern.ch/work/e/ecasilar/GplusbJets/control_plotter.py --plot=3	   --region=1b
python /afs/cern.ch/work/e/ecasilar/GplusbJets/control_plotter.py --plot=4	   --region=1b
python /afs/cern.ch/work/e/ecasilar/GplusbJets/control_plotter.py --plot=5	   --region=1b
python /afs/cern.ch/work/e/ecasilar/GplusbJets/control_plotter.py --plot=6	   --region=1b
python /afs/cern.ch/work/e/ecasilar/GplusbJets/control_plotter.py --plot=7	   --region=1b
python /afs/cern.ch/work/e/ecasilar/GplusbJets/control_plotter.py --plot=8	   --region=1b
python /afs/cern.ch/work/e/ecasilar/GplusbJets/control_plotter.py --plot=9	   --region=1b
python /afs/cern.ch/work/e/ecasilar/GplusbJets/control_plotter.py --plot=10	   --region=1b
python /afs/cern.ch/work/e/ecasilar/GplusbJets/control_plotter.py --plot=11	   --region=1b
python /afs/cern.ch/work/e/ecasilar/GplusbJets/control_plotter.py --plot=0	   --region=2b
python /afs/cern.ch/work/e/ecasilar/GplusbJets/control_plotter.py --plot=1	   --region=2b
python /afs/cern.ch/work/e/ecasilar/GplusbJets/control_plotter.py --plot=2	   --region=2b
python /afs/cern.ch/work/e/ecasilar/GplusbJets/control_plotter.py --plot=3	   --region=2b
python /afs/cern.ch/work/e/ecasilar/GplusbJets/control_plotter.py --plot=4	   --region=2b
python /afs/cern.ch/work/e/ecasilar/GplusbJets/control_plotter.py --plot=5	   --region=2b
python /afs/cern.ch/work/e/ecasilar/GplusbJets/control_plotter.py --plot=6	   --region=2b
python /afs/cern.ch/work/e/ecasilar/GplusbJets/control_plotter.py --plot=7	   --region=2b
python /afs/cern.ch/work/e/ecasilar/GplusbJets/control_plotter.py --plot=8	   --region=2b
python /afs/cern.ch/work/e/ecasilar/GplusbJets/control_plotter.py --plot=9	   --region=2b
python /afs/cern.ch/work/e/ecasilar/GplusbJets/control_plotter.py --plot=10	   --region=2b
python /afs/cern.ch/work/e/ecasilar/GplusbJets/control_plotter.py --plot=11	   --region=2b
python /afs/cern.ch/work/e/ecasilar/GplusbJets/control_plotter.py --plot=0 --region=presel
python /afs/cern.ch/work/e/ecasilar/GplusbJets/control_plotter.py --plot=1 --region=presel
python /afs/cern.ch/work/e/ecasilar/GplusbJets/control_plotter.py --plot=2 --region=presel
python /afs/cern.ch/work/e/ecasilar/GplusbJets/control_plotter.py --plot=3 --region=presel
python /afs/cern.ch/work/e/ecasilar/GplusbJets/control_plotter.py --plot=4 --region=presel
python /afs/cern.ch/work/e/ecasilar/GplusbJets/control_plotter.py --plot=5 --region=presel
python /afs/cern.ch/work/e/ecasilar/GplusbJets/control_plotter.py --plot=6 --region=presel
python /afs/cern.ch/work/e/ecasilar/GplusbJets/control_plotter.py --plot=7 --region=presel
python /afs/cern.ch/work/e/ecasilar/GplusbJets/control_plotter.py --plot=8 --region=presel
python /afs/cern.ch/work/e/ecasilar/GplusbJets/control_plotter.py --plot=9 --region=presel
python /afs/cern.ch/work/e/ecasilar/GplusbJets/control_plotter.py --plot=10 --region=presel
python /afs/cern.ch/work/e/ecasilar/GplusbJets/control_plotter.py --plot=11 --region=presel
