python control_plotter.py --region=presel --plot=Photon_pt              --s_samp=GJets_DR_0p4_HT 
python control_plotter.py --region=presel --plot=Photon_eta             --s_samp=GJets_DR_0p4_HT
python control_plotter.py --region=presel --plot=Photon_phi		--s_samp=GJets_DR_0p4_HT
python control_plotter.py --region=presel --plot=PV_npvsGood		--s_samp=GJets_DR_0p4_HT
python control_plotter.py --region=presel --plot=Photon_pfRelIso03_all	--s_samp=GJets_DR_0p4_HT
python control_plotter.py --region=presel --plot=Photon_pfRelIso03_chg	--s_samp=GJets_DR_0p4_HT
python control_plotter.py --region=presel --plot=Photon_r9   		--s_samp=GJets_DR_0p4_HT
python control_plotter.py --region=presel --plot=Photon_hoe   		--s_samp=GJets_DR_0p4_HT
python control_plotter.py --region=presel --plot=Photon_sieie   	--s_samp=GJets_DR_0p4_HT	
python control_plotter.py --region=presel --plot=LJet_pt   		--s_samp=GJets_DR_0p4_HT
python control_plotter.py --region=presel --plot=LJet_phi   		--s_samp=GJets_DR_0p4_HT
python control_plotter.py --region=presel --plot=nBJet   		--s_samp=GJets_DR_0p4_HT
python control_plotter.py --region=presel --plot=nJet   		--s_samp=GJets_DR_0p4_HT
python control_plotter.py --region=presel --plot=MET_pt   		--s_samp=GJets_DR_0p4_HT
